# -*- coding: utf-8 -*-
"""Copy of NLP_Basics_Revised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194x1QlpJ4G_0OZqDLwrUJ0fQt2fQ7rbX

NAME : Om Nikam
PRN : 202301070006
BATCH : T3

# 🧠 NLP Basics — Revised & Annotated Study Guide

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/)

A comprehensive, beginner-friendly notebook for **Natural Language Processing (NLP)** using Python.
Every section includes:
- 📖 **Concept explanation**
- 💡 **Annotated code examples**
- ✅ **Expected output**

---

## 📚 Table of Contents
1. [Setup & Installations](#setup)
2. [Tokenization](#tokenization)
3. [Stop Words Removal](#stopwords)
4. [Stemming & Lemmatization](#stemlem)
5. [Part-of-Speech (POS) Tagging](#pos)
6. [Named Entity Recognition (NER)](#ner)
7. [Bag of Words (BoW)](#bow)
8. [TF-IDF](#tfidf)
9. [Word Embeddings (Word2Vec)](#word2vec)
10. [Sentiment Analysis](#sentiment)
11. [Text Similarity & Cosine Distance](#similarity)
12. [N-Grams](#ngrams)
13. [spaCy Visualization](#viz)
14. [Naive Bayes Text Classifier](#nb)

---

## 1. ⚙️ Setup & Installations

Install all required libraries. Run this cell first — it may take a few minutes.

**Libraries used:**
- `nltk` — classic NLP toolkit (tokenizing, stemming, corpora)
- `spacy` — fast, production-ready NLP (NER, POS, dependency parsing)
- `scikit-learn` — ML toolkit (BoW, TF-IDF, Naive Bayes)
- `gensim` — topic modeling & Word2Vec embeddings
- `transformers` — Hugging Face models (BERT, sentiment analysis)
- `torch` — required backend for Hugging Face Transformers
"""

# Install all required packages
# Run once per Colab session
!pip install nltk spacy scikit-learn gensim transformers torch pandas --quiet

# Download the spaCy English model (small, fast)
!python -m spacy download en_core_web_sm --quiet

import nltk
# Download NLTK datasets needed for this notebook
nltk.download(['punkt', 'stopwords', 'wordnet', 'averaged_perceptron_tagger', 'vader_lexicon'])

print("✅ All packages installed successfully!")

import nltk

# Download NLTK datasets needed for this notebook
nltk.download('punkt')           # Tokenizer
nltk.download('punkt_tab')       # Updated tokenizer tables
nltk.download('stopwords')       # Common stop words list
nltk.download('averaged_perceptron_tagger_eng')  # Updated POS tagger
nltk.download('wordnet')         # Lemmatizer dictionary
nltk.download('maxent_ne_chunker_tab') # Updated NER chunker
nltk.download('words')           # English word list
nltk.download('vader_lexicon')   # VADER sentiment lexicon

print("✅ NLTK data downloaded!")

"""---
## 2. ✂️ Tokenization

**What is it?**  
Tokenization splits raw text into smaller units called **tokens** — usually words or sentences.
It's always the **first step** in any NLP pipeline.

**Two types:**
- **Word tokenization** → `"Hello world"` → `["Hello", "world"]`
- **Sentence tokenization** → splits a paragraph into individual sentences

**Why it matters:**  
Computers can't understand raw strings. Breaking text into tokens makes it processable.

**NLTK vs spaCy:**
- NLTK is great for learning and experimentation
- spaCy is faster and handles edge cases like contractions better
"""

from nltk.tokenize import word_tokenize, sent_tokenize

# --- Sample text from spam.csv ---
# Using a common format found in these datasets
text = "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

# --- Word Tokenization ---
# Splits text into individual words AND punctuation marks
word_tokens = word_tokenize(text)
print("📝 Original text:")
print(text)
print("\n🔤 Word Tokens:")
print(word_tokens)
print(f"   → Total tokens: {len(word_tokens)}")

print("\n")

# --- Sentence Tokenization ---
# Splits text into individual sentences using punctuation rules
sent_tokens = sent_tokenize(text)
print("📄 Sentence Tokens:")
for i, sentence in enumerate(sent_tokens, 1):
    print(f"   Sentence {i}: {sentence}")

from nltk.tokenize import word_tokenize, sent_tokenize

# --- Example text ---
text = "Natural Language Processing is fascinating! It helps machines understand human text. Let's explore it."

# --- Word Tokenization ---
# This function splits text into individual words and punctuation marks
word_tokens = word_tokenize(text)
print("🔤 Word Tokens:")
print(word_tokens)
print(f"   → Total tokens: {len(word_tokens)}")

print("\n")

# --- Sentence Tokenization ---
# This function splits text into individual sentences based on punctuation rules
sent_tokens = sent_tokenize(text)
print("📄 Sentence Tokens:")
for i, sentence in enumerate(sent_tokens, 1):
    print(f"   Sentence {i}: {sentence}")

import spacy

# Load the small English model previously downloaded
nlp = spacy.load("en_core_web_sm")

# --- spaCy Tokenization ---
# Segment text and automatically handle contractions like "Don't"
doc = nlp("Don't forget to buy milk — and eggs!")

print("🔤 spaCy Tokens with attributes:")
for token in doc:
    # Access individual token text and built-in linguistic attributes
    print(f"   Token: {token.text:<15} | Is punct: {token.is_punct} | Is alpha: {token.is_alpha}")

"""---
## 3. 🚫 Stop Words Removal

**What are stop words?**  
Very common words like *is*, *the*, *and*, *in*, *a* that usually **don't carry meaning** for NLP tasks.

**When to remove them:**  
- ✅ Text classification, sentiment analysis, topic modeling
- ❌ Machine translation, grammar correction (order & structure matter)

**Tip:** spaCy has ~326 stop words; NLTK has ~179. Use spaCy for broader coverage.
"""

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import spacy

nlp = spacy.load("en_core_web_sm")

# --- Compare stop word lists ---
ltk_stopwords = set(stopwords.words('english'))
spacy_stopwords = spacy.lang.en.stop_words.STOP_WORDS

print(f"📊 NLTK stop words count:  {len(ltk_stopwords)}")
print(f"📊 spaCy stop words count: {len(spacy_stopwords)}")
print()

# --- Removing stop words with NLTK ---
sentence = "Larry Page founded Google in the United States in the early 1990s."
tokens = word_tokenize(sentence.lower())  # Lowercase for consistent matching

# Keep only tokens that are NOT in the stop words list
filtered_nltk = [word for word in tokens if word not in ltk_stopwords]

print(f"📝 Original: {sentence}")
print(f"🔤 All tokens:       {tokens}")
print(f"✅ NLTK filtered:    {filtered_nltk}")
print()

# --- Removing stop words with spaCy ---
# token.is_stop is a built-in boolean attribute — no manual list needed!
doc = nlp(sentence)
filtered_spacy = [token.text for token in doc if not token.is_stop and not token.is_punct]
print(f"✅ spaCy filtered:   {filtered_spacy}")

import nltk

try:
    nltk.data.find('corpora/stopwords')
    print("'stopwords' resource already downloaded.")
except LookupError:
    print("Downloading NLTK 'stopwords' resource...")
    nltk.download('stopwords', quiet=True)
    print("'stopwords' download complete.")

print("✅ NLTK stopwords data ensured!")

"""---
## 4. 🌱 Stemming & Lemmatization

Both techniques reduce words to a **root/base form** to group related words.

| Technique | Output | Example | Speed |
|---|---|---|---|
| **Stemming** | Root (may not be a real word) | `studies` → `studi` | Fast |
| **Lemmatization** | Real dictionary word | `studies` → `study` | Slower |

**Rule of thumb:**  
Use stemming for search engines (speed matters). Use lemmatization for chatbots and generation (quality matters).
"""

from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

# --- Stemming ---
# PorterStemmer applies heuristic rules to strip suffixes
porter = PorterStemmer()
words = ['running', 'runs', 'runner', 'easily', 'fairly', 'studies', 'studying', 'studied']

print("✂️ Stemming (PorterStemmer):")
for word in words:
    stemmed = porter.stem(word)
    print(f"   {word:<15} → {stemmed}")

print()

# --- Lemmatization ---
# WordNetLemmatizer links words to their actual dictionary base
lemmatizer = WordNetLemmatizer()

print("📖 Lemmatization (WordNetLemmatizer):")
# Note: You must provide a POS (Part-of-Speech) hint for accurate results
word_pos_pairs = [
    ('running', 'v'), ('studies', 'v'), ('better', 'a'),
    ('geese', 'n'), ('wolves', 'n'), ('is', 'v')
]
for word, pos in word_pos_pairs:
    lemma = lemmatizer.lemmatize(word, pos=pos)
    print(f"   {word:<15} → {lemma}  (POS hint: {pos})")

import spacy

# Load the previously downloaded English model
nlp = spacy.load("en_core_web_sm")

# Define a sentence with various plural nouns and past-tense verbs
doc = nlp("The children were running faster than ever. The geese flew away.")

print("📖 spaCy Lemmatization (context-aware):")
print(f"  {'Token':<20} {'Lemma':<20} {'POS'}")
print("-" * 55)

for token in doc:
    # Filter out common 'stop words', punctuation, and spaces for clarity
    if not token.is_stop and not token.is_punct and not token.is_space:
        # .lemma_ returns the string form of the lemma
        # .pos_ returns the coarse-grained Part-of-Speech tag
        print(f"  {token.text:<20} {token.lemma_:<20} {token.pos_}")

"""---
## 5. 🏷️ Part-of-Speech (POS) Tagging

**What is it?**  
Assigning a grammatical label to each word — noun, verb, adjective, etc.

**Common POS Tags:**

| Tag | Meaning | Example |
|---|---|---|
| NN | Noun, singular | `dog`, `city` |
| VB | Verb, base form | `run`, `eat` |
| JJ | Adjective | `big`, `fast` |
| RB | Adverb | `quickly`, `very` |
| DT | Determiner | `the`, `a` |
| IN | Preposition | `in`, `on`, `at` |

**Why useful?**  
Resolves ambiguity: "bank" (noun = financial institution vs. verb = to bank money)
"""

import nltk
from nltk import pos_tag, word_tokenize

# --- NLTK POS Tagging ---
sentence = "Google is a technology company known for its search engine and Android operating system."
tokens = word_tokenize(sentence)

# Ensure the required resources are downloaded
nltk.download('averaged_perceptron_tagger_eng', quiet=True)
nltk.download('tagsets_json', quiet=True) # <--- This fix prevents the LookupError

# pos_tag() returns list of (word, tag) tuples
tagged = pos_tag(tokens)

print("🏷️ NLTK POS Tags:")
for word, tag in tagged:
    print(f"   {word:<15} → {tag}")

print("\n💡 Tag explanations:")
# Access NLTK's built-in documentation for specific tags
tags_to_explain = ['NNP', 'VBZ', 'DT', 'NN', 'VBG', 'IN']
for tag in tags_to_explain:
    try:
        nltk.help.upenn_tagset(tag)
    except:
        print(f"{tag}: Explanation unavailable.")

import nltk

# Check for the resource that provides POS tag descriptions
try:
    # Attempt to locate the data in your environment
    nltk.data.find('help/tagsets_json')
    print("'tagsets_json' resource already downloaded.")
except LookupError:
    # Download the resource if missing (approx. 100KB)
    print("Downloading NLTK 'tagsets_json' resource...")
    nltk.download('tagsets_json', quiet=True)
    print("'tagsets_json' download complete.")

print("✅ NLTK 'tagsets_json' data ensured!")

import nltk

# Attempt to find the specific English POS tagging model
try:
    nltk.data.find('taggers/averaged_perceptron_tagger_eng')
    print("'averaged_perceptron_tagger_eng' resource already downloaded.")
except LookupError:
    # Download the required tagger resource if it's missing
    print("Downloading NLTK 'averaged_perceptron_tagger_eng' resource...")
    nltk.download('averaged_perceptron_tagger_eng', quiet=True)
    print("'averaged_perceptron_tagger_eng' download complete.")

print("✅ NLTK 'averaged_perceptron_tagger_eng' data ensured!")

# --- spaCy POS Tagging (coarse + fine-grained) ---
sentence = "Apple is looking at buying a U.K. startup for $1 billion."
# The nlp() object automatically tokenizes, tags, and parses the text
doc = nlp(sentence)

print("🏷️  spaCy POS Tags:")
print(f"  {'Token':<15} {'Coarse POS':<15} {'Fine Tag':<15} {'Dependency'}")
print("-" * 60)

for token in doc:
    # .pos_ = Coarse-grained POS (e.g., PROPN)
    # .tag_ = Fine-grained POS (e.g., NNP)
    # .dep_ = Syntactic dependency (e.g., nsubj)
    print(f"  {token.text:<15} {token.pos_:<15} {token.tag_:<15} {token.dep_}")

"""---
## 6. 🔎 Named Entity Recognition (NER)

**What is it?**  
NER identifies and classifies real-world entities in text — people, companies, locations, dates, money.

**spaCy Entity Types:**
- `PERSON` — People, including fictional
- `ORG` — Companies, agencies, institutions
- `GPE` — Countries, cities, states
- `DATE` — Dates or time periods
- `MONEY` — Monetary values
- `LOC` — Non-GPE locations (rivers, mountains)
- `PRODUCT` — Objects, vehicles, foods

**Use cases:** Information extraction, knowledge graphs, financial document parsing, news analysis.
"""

import spacy
from collections import Counter

# Load the core English model
nlp = spacy.load("en_core_web_sm")

text = (
    "Elon Musk, the CEO of Tesla and SpaceX, announced on Tuesday that "
    "the company raised $2.3 billion in funding. The headquarters is "
    "located in Austin, Texas."
)

# Process the text
doc = nlp(text)

print("🔎 Named Entities Found:")
print(f"  {'Entity':<25} {'Label':<12} {'Description'}")
print("-" * 65)

# doc.ents contains the recognized entities
for ent in doc.ents:
    # ent.text is the original text; ent.label_ is the category
    # spacy.explain() provides a human-readable definition of the tag
    print(f"  {ent.text:<25} {ent.label_:<12} {spacy.explain(ent.label_)}")

print()

# Use Counter to see which entity types appear most frequently
entity_counts = Counter([ent.label_ for ent in doc.ents])
print("📊 Entity Type Distribution:")
for label, count in entity_counts.most_common():
    print(f"   {label}: {count}")

# --- Extract specific entity types from text ---
news = (
    "Microsoft acquired Activision Blizzard for $68.7 billion in January 2023. "
    "The deal was reviewed by the UK Competition and Markets Authority. "
    "Satya Nadella, CEO of Microsoft, said this accelerates the gaming strategy."
)

# Process the news string with the nlp pipeline
doc = nlp(news)

# Use list comprehensions to filter entities by their specific label_ string
# This is great for creating structured lists from unstructured sentences!
orgs   = [ent.text for ent in doc.ents if ent.label_ == 'ORG']
money  = [ent.text for ent in doc.ents if ent.label_ == 'MONEY']
people = [ent.text for ent in doc.ents if ent.label_ == 'PERSON']
dates  = [ent.text for ent in doc.ents if ent.label_ == 'DATE']

print("🏢 Organizations:", orgs)
print("💰 Money:        ", money)
print("👤 People:       ", people)
print("📅 Dates:        ", dates)

from nltk import word_tokenize, pos_tag, ne_chunk
from nltk.tree import Tree

sentence = "Barack Obama was the 44th President of the United States."

# Step 1 & 2: Tokenize and Tag POS
# ne_chunk requires POS tags to identify proper nouns (NNP)
tokens = word_tokenize(sentence)
pos_tags = pos_tag(tokens)

# Step 3: Identify Named Entity spans
chunks = ne_chunk(pos_tags)

print("🔎 NLTK Named Entities:")
for subtree in chunks:
    # Entities are stored as Tree objects in the chunked result
    if isinstance(subtree, Tree):
        # Join words in the entity span (e.g., "Barack" + "Obama")
        entity_name = " ".join([word for word, tag in subtree.leaves()])
        # Extract the label (e.g., PERSON, GPE)
        entity_label = subtree.label()
        print(f"   [{entity_label}] {entity_name}")

import nltk

# Attempt to locate the Maximum Entropy NE Chunker tables
try:
    nltk.data.find('chunkers/maxent_ne_chunker_tab')
    print("'maxent_ne_chunker_tab' resource already downloaded.")
except LookupError:
    # Download the required resource if it is missing from the environment
    print("Downloading NLTK 'maxent_ne_chunker_tab' resource...")
    nltk.download('maxent_ne_chunker_tab', quiet=True)
    print("'maxent_ne_chunker_tab' download complete.")

print("✅ NLTK 'maxent_ne_chunker_tab' data ensured!")

"""Example (Customized):
Imagine our total vocabulary from all documents is: [buy, cash, free, gift, now, win]

Doc 1: "buy now win free gift" → [1, 0, 1, 1, 1, 1]

Doc 2: "cash cash buy now" → [1, 2, 0, 0, 1, 0]

Pros:

Simple: Easy to understand and implement.

Interpretable: You can easily see which words appear most in different categories.

Fast: Computationally efficient for many tasks.

Cons:

Ignores Order: "Man bites dog" and "Dog bites man" result in the exact same vector.

No Semantic Meaning: It doesn't understand that "buy" and "purchase" are similar.

Sparsity: With large vocabularies, vectors become mostly zeros, which is memory-intensive.
"""

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Customized corpus related to your spam dataset
corpus = [
    "win free cash now",
    "cash prize winner",
    "free gift for you",
    "win a free prize"
]

# Step 1: Initialize the vectorizer
# This builds the vocabulary and performs the counts
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

# Step 2: Extract feature names (our vocabulary)
feature_names = vectorizer.get_feature_names_out()

# Step 3: Create a readable table (DataFrame)
df_bow = pd.DataFrame(X.toarray(), columns=feature_names,
                      index=[f"Msg {i+1}" for i in range(len(corpus))])

print("📊 Bag of Words Count Matrix:")
print(df_bow)
print("\n📚 Vocabulary:", list(feature_names))

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Updated corpus reflecting your spam detection task
corpus = [
    "win free cash now",
    "win a free gift",
    "cash prize winner",
    "free gift for you"
]

# Initialize CountVectorizer to build vocabulary and count occurrences
vectorizer = CountVectorizer()

# fit_transform learns the vocabulary and converts the text to a matrix
X = vectorizer.fit_transform(corpus)

# Get the list of unique words (features) learned by the vectorizer
feature_names = vectorizer.get_feature_names_out()

# Convert the sparse matrix into a readable pandas DataFrame
df_bow = pd.DataFrame(X.toarray(), columns=feature_names,
                      index=[f"Msg {i+1}" for i in range(len(corpus))])

print("📊 Bag of Words Count Matrix (Spam Example):")
print(df_bow)
print("\n📚 Vocabulary:", list(feature_names))
print("\n💡 Each number represents how many times that word appears in that specific message.")

"""TF-IDF (Term Frequency — Inverse Document Frequency)
What to paste in your Text Box:

What is it?
An improvement over Bag of Words that weights words by importance, not just how many times they appear.

The Intuition:

TF (Term Frequency): How often a word appears in a specific message.

IDF (Inverse Document Frequency): Reduces the weight of words that appear in almost every message (like "the", "is", "to").

Why it's better for Spam:
A word like "WINNER" might appear many times in one spam email but rarely in your normal emails. TF-IDF gives "WINNER" a high score and "the" a low score.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Customized Spam/Ham corpus
messages = [
    "WINNER! Claim your cash prize now by calling our claim line.",
    "Hey, are we still going to the prize giving ceremony tonight?",
    "URGENT! Your cash balance is low. Call now for a prize.",
    "I will be there at 8pm for the ceremony."
]

# Initialize TF-IDF Vectorizer
# We remove 'english' stop words to get cleaner results
tfidf = TfidfVectorizer(stop_words='english')
X_tfidf = tfidf.fit_transform(messages)
feature_names = tfidf.get_feature_names_out()

# Convert to DataFrame for easy viewing
df_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=feature_names,
                       index=[f"Msg {i+1}" for i in range(len(messages))])

print("📐 TF-IDF Importance Matrix (Spam vs. Ham Keywords):")
# Showing a few key columns to see the difference
print(df_tfidf[['cash', 'prize', 'winner', 'ceremony', 'urgent']].round(3))

print("\n💡 Notice: 'cash' has a high score in Msg 1 and 3, but 0.0 in others.")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer # Keep existing import for CountVectorizer if it was there previously or for consistency.
import pandas as pd

# --- Extract top keywords per document ---
articles = [
    "Python is a popular programming language. Python is used for data science and machine learning.",
    "Football is a popular sport. The World Cup is the biggest football tournament in the world.",
    "Dogs are loyal animals. Many people keep dogs as pets. Dogs need daily exercise."
]

tfidf = TfidfVectorizer(stop_words='english')
X = tfidf.fit_transform(articles)
feature_names = tfidf.get_feature_names_out()

print("🔑 Top Keywords per Document (by TF-IDF score):")
for i, article in enumerate(articles):
    scores = X[i].toarray()[0]
    top_indices = scores.argsort()[::-1][:3]  # Get indices of top 3
    top_words = [(feature_names[j], scores[j]) for j in top_indices if scores[j] > 0]
    print(f"\n  Doc {i+1}: ...{article[:45]}...")
    for word, score in top_words:
        print(f"     [{word}] → score: {score:.4f}")

"""---
## 9. 🔢 Word Embeddings (Word2Vec)
🔢 Word Embeddings (Word2Vec)What are word embeddings?Word embeddings are dense vector representations where semantically similar words are placed close to each other in a multi-dimensional vector space. Unlike Bag of Words or TF-IDF, which create sparse vectors based on word counts, embeddings capture the "meaning" and relationships between words.Key Differences:Meaning Capture: Embeddings can solve analogies like $king - man + woman \approx queen$.Dimensions: Vectors are typically dense (100–300 dimensions) rather than the size of the entire vocabulary.Context: They rely on the distributional hypothesis: "A word is known by the company it keeps".Word2Vec Approaches:CBOW (Continuous Bag of Words): Predicts a target word based on its surrounding context.Skip-gram: Predicts the surrounding context words given a single target word.
"""

from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

# Step 1: Training Corpus
# In practice, Word2Vec needs millions of sentences to learn meaningful patterns.
sentences = [
    "The king is a powerful man who rules the kingdom",
    "The queen is a powerful woman who rules the kingdom",
    "The man likes to play football and watch movies",
    "The woman likes to read books and paint pictures",
    "Dogs are loyal animals and make wonderful pets",
    "Cats are independent animals and make wonderful pets",
    "Paris is the beautiful capital city of France",
    "Berlin is the historic capital city of Germany",
    "Machine learning and deep learning are subfields of AI",
    "Natural language processing is a subfield of AI"
]

# Step 2: Tokenization
# word_tokenize converts raw strings into lists of lowercase tokens.
tokenized = [word_tokenize(s.lower()) for s in sentences]

# Step 3: Train Word2Vec Model
model = Word2Vec(
    sentences=tokenized,
    vector_size=50,   # Dimensionality of the embedding space
    window=3,         # How many words to look at on each side
    min_count=1,      # Include all words (even those that appear once)
    workers=2,        # CPU threads used for training
    epochs=100        # Passes over the training data
)

print("✅ Word2Vec model trained!")
print(f"📚 Vocabulary size: {len(model.wv.key_to_index)} words")

# Step 4: Semantic Similarity
# Finding words with the highest cosine similarity to 'king'.
print('\n🔍 Words most similar to king:')
for word, sim in model.wv.most_similar('king', topn=4):
    print(f"   {word:<15} cosine similarity: {sim:.4f}")

# Step 5: Inspecting the Vector
# Each word is represented by 50 floats (the embedding).
print('\n📐 First 8 dimensions of vector for king:')
print(model.wv['king'][:8].round(4))

# --- Compare word pair similarities ---
# Cosine similarity range: 1.0 (identical) to -1.0 (opposite)
pairs = [
    ('king', 'queen'),
    ('dog', 'cat'),
    ('paris', 'berlin'),
    ('man', 'woman'),
    ('king', 'dog'),    # Expected to be much lower
]

print("📊 Word Pair Cosine Similarities:")
for w1, w2 in pairs:
    try:
        # wv.similarity calculates the cosine distance between two word vectors
        sim = model.wv.similarity(w1, w2)
        print(f"   {w1} ↔ {w2}: {sim:.4f}")
    except KeyError as e:
        # Word2Vec can only compare words that were in the training 'sentences'
        print(f"   ⚠️ Not in vocab: {e}")

"""---
## 10. 😊 Sentiment Analysis

**What is it?**  
Classifying the **emotional tone** of text as positive, negative, or neutral.

**Two approaches covered here:**
1. **VADER** (Valence Aware Dictionary and sEntiment Reasoner)  
   - Lexicon-based, rule-based
   - Fast, no model download, great for social media text
   - Returns: pos/neg/neu proportions + compound score (-1 to +1)

2. **Transformers (Hugging Face pipeline)**  
   - Pre-trained deep learning model (DistilBERT by default)
   - More accurate, handles context and nuance
   - Requires model download (~270MB)
"""

from nltk.sentiment.vader import SentimentIntensityAnalyzer

# VADER: Valence Aware Dictionary and sEntiment Reasoner
vader = SentimentIntensityAnalyzer()

# Updated examples to reflect spam-like and normal-like messages
texts = [
    "Congratulations! You've won a $1,000 Walmart gift card. Click now!",
    "I'm so sorry, I can't make it to the meeting today. My apologies.",
    "The weather is okay today. Not too sunny, not too rainy.",
    "URGENT: Your account has been hacked. We are very concerned.",
    "I love our new project! It is going to be amazing! 🚀"
]

print("⚡ VADER Sentiment Results:")
print("(compound score: +1=most positive, -1=most negative, threshold ±0.05)")
print("-" * 70)

for text in texts:
    # polarity_scores calculates pos, neg, neu, and compound values
    scores = vader.polarity_scores(text)
    compound = scores['compound']

    # Standard VADER thresholding
    if compound >= 0.05:
        overall = "POSITIVE ✅"
    elif compound <= -0.05:
        overall = "NEGATIVE ❌"
    else:
        overall = "NEUTRAL  ⚪"

    print(f"Text: {text[:55]}")
    print(f"  → {overall} | compound: {compound:.4f} | pos:{scores['pos']:.2f} neg:{scores['neg']:.2f}")
    print()

from transformers import pipeline

# The pipeline automatically downloads the 'distilbert-base-uncased-finetuned-sst-2-english' model
print("⏳ Loading transformer model (may take ~30s on first run)...")
classifier = pipeline('sentiment-analysis')
print("✅ Model ready!\n")

# Let's use messages that could be found in a messaging dataset
sentences = [
    "You have won a guaranteed $1000 cash prize! Claim it now.",
    "I'm really sorry but I won't be able to finish the report by Friday.",
    "The product is decent, but the delivery was quite late.",
    "I am absolutely thrilled with the results of our collaboration!"
]

print("🤖 Transformer Sentiment Results:")
print("-" * 65)

for sentence in sentences:
    # Pass the text to the classifier; it returns a list containing a dictionary
    result = classifier(sentence)[0]
    label = result['label']
    score = result['score']

    icon = '✅' if label == 'POSITIVE' else '❌'

    # Label is either 'POSITIVE' or 'NEGATIVE'
    # Score represents the confidence level
    print(f"{icon} [{label}] — confidence: {score:.2%}")
    print(f"   {sentence[:60]}...")
    print()

"""---
## 11. 📏 Text Similarity & Cosine Distance
Text Similarity & Cosine Distance
What is it?
Text similarity is the process of measuring how close two pieces of text are to each other, typically expressed as a number between 0 and 1.

Cosine Similarity:

Mechanism: It compares the direction of two vectors in a high-dimensional space rather than their magnitude.

Scores: A score of 1.0 indicates the texts are identical in direction, while 0.0 means they are completely different.

Compatibility: This method works exceptionally well with TF-IDF vectors and word embeddings.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Updated messages: Two are spam-related, two are business-related
documents = [
    "WINNER! Claim your cash prize and reward now.",
    "Get your cash reward by calling our prize line today.",
    "Please review the attached project proposal for the meeting.",
    "The team meeting for the new project is scheduled for Friday.",
]

# Step 1: Convert text to TF-IDF vectors
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)

# Step 2: Compute pairwise cosine similarity
# This compares every document against every other document
sim_matrix = cosine_similarity(tfidf_matrix)

print("📏 Cosine Similarity Matrix (0=different, 1=identical):")
print("        Msg0   Msg1   Msg2   Msg3")
for i, row in enumerate(sim_matrix):
    scores = '  '.join([f'{s:.3f}' for s in row])
    print(f"  Msg{i}: {scores}")

print("\n🔍 Finding messages most similar to Msg 0 (Spam Example):")
# Rank the messages based on their similarity to the first spam message
scores_for_msg0 = sim_matrix[0]
ranked = np.argsort(scores_for_msg0)[::-1]

for idx in ranked:
    print(f"   Msg{idx} (score: {scores_for_msg0[idx]:.3f}): {documents[idx]}")

"""---
## 12. 🔗 N-Grams
🔗 N-Grams
What are N-Grams? N-Grams are contiguous sequences of N consecutive items (usually words) from a given sample of text. They help models understand the local context of words rather than treating them as isolated units.
N,Name,"Example: ""the cat sat'''
1,Unigram,"[""the"", ""cat"", ""sat""]"
2,Bigram,"[(""the"", ""cat""), (""cat"", ""sat"")]"
3,Trigram,"[(""the"", ""cat"", ""sat"")]"

"""

from nltk import ngrams, word_tokenize, FreqDist

# Sample text inspired by common spam/ham patterns
text = "Claim your cash prize now. To claim your prize, call our claim line."
tokens = word_tokenize(text.lower())

# --- Generate bigrams and trigrams ---
# ngrams() creates a generator of consecutive word tuples
bigrams_  = list(ngrams(tokens, 2))
trigrams_ = list(ngrams(tokens, 3))

print(f"🔤 Tokens: {tokens}\n")
print(f"🔗 Bigrams ({len(bigrams_)} total):")
print(bigrams_)

print(f"\n🔗 Trigrams ({len(trigrams_)} total):")
print(trigrams_)

print("\n📊 Top 3 most common bigrams:")
# FreqDist calculates the frequency of each N-Gram
freq = FreqDist(bigrams_)
for bigram, count in freq.most_common(3):
    print(f"   {bigram} → {count}")

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Updated corpus reflecting spam-related phrases
corpus = [
    "claim your prize now",
    "prize winner claim now",
    "please claim your prize"
]

# ngram_range=(2,2) ensures we only look at two-word phrases
bigram_vec = CountVectorizer(ngram_range=(2, 2))
X = bigram_vec.fit_transform(corpus)

# Create a DataFrame to see which messages contain which phrases
df_ngrams = pd.DataFrame(X.toarray(), columns=bigram_vec.get_feature_names_out(),
                         index=[f"Msg{i+1}" for i in range(len(corpus))])

print("📊 Bigram Count Matrix (Spam Phrases):")
print(df_ngrams)

"""---
## 13. 🎨 spaCy Visualization (displaCy)
What is it?
spaCy includes a powerful built-in visualizer called displaCy. It allows you to see the results of NLP processing—such as how words relate to each other or where specific entities are located—directly in your browser or notebook.

Two main visualization styles:

style='dep' (Dependency Parse Tree): This shows the grammatical structure of a sentence. It uses arrows to show relationships like which word is the subject (nsubj) or which word modifies another.

style='ent' (Entity Highlighting): This highlights named entities (like people, dates, or organizations) directly within the text using color-coded labels.
"""

import spacy
from spacy import displacy

# Load the English model
nlp = spacy.load("en_core_web_sm")

# --- Dependency Parse Tree ---
# We use a sample message to see its grammatical structure
doc = nlp("You have won a guaranteed cash prize.")

print("🌳 Dependency Parse Tree:")
# jupyter=True is required to render the SVG image directly in the Colab cell
displacy.render(doc, style='dep', jupyter=True)

import spacy
from spacy import displacy

# Load the small English model (en_core_web_sm)
nlp = spacy.load("en_core_web_sm")

# We create a document containing names, organizations, dates, and money
text = "Satya Nadella, the CEO of Microsoft, announced a $2 billion investment on Friday in London."
doc = nlp(text)

print("🔎 Named Entity Visualization:")
# style='ent' highlights entities inline
# jupyter=True is required for rendering in Google Colab or Jupyter Notebooks
displacy.render(doc, style='ent', jupyter=True)

# --- Print dependency information without visualization ---
# This example uses a more descriptive sentence to show modifiers
doc = nlp("The old man slowly walked to the quiet library.")

print("🌳 Dependency Relations:")
# Token = the word, POS = part of speech, Dependency = relationship, Head = parent word
print(f"  {'Token':<15} {'POS':<10} {'Dependency':<15} {'Head'}")
print("-" * 55)

for token in doc:
    # token.dep_ provides the grammatical label (e.g., det, amod, nsubj)
    # token.head.text shows which word this token is attached to
    print(f"  {token.text:<15} {token.pos_:<10} {token.dep_:<15} {token.head.text}")

"""---
## 14. 🤖 Naive Bayes Text Classifier

**What is it?**  
A simple but powerful probabilistic classifier based on **Bayes' theorem**.

**Key idea:**
```
P(class | text) ∝ P(class) × P(word1 | class) × P(word2 | class) × ...
```

**Why 'naive'?**  
It assumes all features (words) are **independent** — not true in reality, but works surprisingly well!

**Common variants:**
- `MultinomialNB` — for word counts/frequencies (most common for text)
- `BernoulliNB` — for binary features (word present or not)

**Use cases:** Spam filtering, news topic classification, sentiment classification.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# --- Training data (7 Spam, 7 Ham) ---
texts = [
    "Congratulations! You've won a FREE iPhone. Click here to claim!",
    "URGENT: Your bank account is compromised. Verify NOW!",
    "Win $1000 instantly! No strings attached. Limited offer!",
    "You are selected for a FREE vacation. Act today!",
    "Exclusive deal: 90% off all products. Order now!",
    "Winner! Claim your prize tonight. Special deal expires soon!",
    "Free gift just for you. Claim your reward today!",
    "Hi, are we still meeting for lunch tomorrow at noon?",
    "Please find the quarterly report attached to this email.",
    "Can you review my pull request when you get a chance?",
    "The team meeting has been moved to Thursday at 3pm.",
    "I'll be out of office until Monday. Please email my colleague.",
    "Here are the notes from today's project planning session.",
    "The deadline for the proposal has been extended by one week."
]
labels = [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]

# Step 1: Split into sets. random_state ensures the split is the same every time you run it.
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.25, random_state=42
)

# Step 2: Vectorization with Stop Word removal
vectorizer = TfidfVectorizer(stop_words='english')
X_train_vec = vectorizer.fit_transform(X_train)   # Learns vocabulary and weights
X_test_vec  = vectorizer.transform(X_test)         # Uses learned vocabulary on new data

# Step 3: Train the Naive Bayes Classifier
clf = MultinomialNB()
clf.fit(X_train_vec, y_train)

# Step 4: Make Predictions and Evaluate
y_pred = clf.predict(X_test_vec)

print("📊 Classification Report:")
# target_names makes the output readable (replaces 0/1 with Ham/Spam)
print(classification_report(y_test, y_pred, target_names=['Ham (not spam)', 'Spam']))
print(f"✅ Overall Accuracy: {accuracy_score(y_test, y_pred):.2%}")

# --- Predict on new unseen messages ---
new_messages = [
    "Win a brand new car! Limited time offer. Act now!",
    "Can you send me the updated spreadsheet by end of day?",
    "Exclusive: 90% discount on premium membership today only!",
    "The project deadline has been extended to next Friday."
]

# Step 1: Transform the new text using the training vocabulary
new_vec = vectorizer.transform(new_messages)

# Step 2: Get the hard predictions (0 or 1)
predictions = clf.predict(new_vec)

# Step 3: Get the probability scores for each class
# This returns a list of [prob_ham, prob_spam] for each message
probabilities = clf.predict_proba(new_vec)

print("🔍 Predictions on New Messages:")
print("-" * 65)

for msg, pred, probs in zip(new_messages, predictions, probabilities):
    # Mapping the numeric prediction to a readable label
    label = '🚨 SPAM' if pred == 1 else '✅ HAM '

    # max(probs) gives the confidence score for the chosen label
    confidence = max(probs)

    print(f"{label} (confidence: {confidence:.2%})")
    print(f"   Text: {msg}")
    print()

import nltk
import random
from nltk.corpus import movie_reviews
from nltk.classify import NaiveBayesClassifier
from nltk.classify.util import accuracy

# --- ENSURE DATA IS DOWNLOADED ---
try:
    nltk.data.find('corpora/movie_reviews')
    print("✅ 'movie_reviews' resource already found.")
except LookupError:
    print("⏳ Downloading NLTK 'movie_reviews' resource (this may take a moment)...")
    nltk.download('movie_reviews', quiet=True)
    print("✅ Download complete.")

# Step 1: Define which features (words) the model should look for
def word_features(words, top_words):
    """Returns a dictionary: {word: True} if word is in the review, else False"""
    word_set = set(words)
    return {word: (word in word_set) for word in top_words}

# Step 2: Build the 'Vocabulary' (The top 2,000 most frequent words)
all_words = nltk.FreqDist(w.lower() for w in movie_reviews.words())
top_words = list(all_words.keys())[:2000]

# Step 3: Create labeled feature sets
feature_sets = [
    (word_features(movie_reviews.words(fileid), top_words), category)
    for category in movie_reviews.categories()
    for fileid in movie_reviews.fileids(category)
]

# Step 4: Shuffle and Split (Standard 75/25 split)
random.seed(42)
random.shuffle(feature_sets)
train_set, test_set = feature_sets[:1500], feature_sets[1500:]

# Step 5: Train the NLTK Naive Bayes Classifier
nb_clf = NaiveBayesClassifier.train(train_set)

print(f"📈 Movie Review Classifier Accuracy: {accuracy(nb_clf, test_set):.2%}")
print("\n🔑 Most informative features (Top 10):")
nb_clf.show_most_informative_features(10)

"""---
## 🎯 Summary & Quick Reference

| Concept | Library | Best Use Case |
|---|---|---|
| Tokenization | NLTK / spaCy | First step in every NLP pipeline |
| Stop Words Removal | NLTK / spaCy | Reduce noise in text features |
| Stemming | NLTK (PorterStemmer) | Fast word normalization (search engines) |
| Lemmatization | NLTK / spaCy | Accurate normalization (chatbots, generation) |
| POS Tagging | NLTK / spaCy | Grammar analysis, disambiguation |
| NER | spaCy / NLTK / Flair | Extract real-world entities |
| Bag of Words | sklearn | Simple text features for classification |
| TF-IDF | sklearn | Weighted features highlighting key terms |
| Word2Vec | gensim | Semantic word vector representations |
| Sentiment Analysis | Transformers / VADER | Classify emotional tone |
| Cosine Similarity | sklearn | Measure document similarity |
| N-Grams | NLTK / sklearn | Phrase-aware text features |
| Naive Bayes | sklearn / NLTK | Fast, interpretable text classification |

---

### 📚 Next Steps to Level Up
- **Hugging Face `pipeline()`** — zero-shot classification, QA, summarization
- **Fine-tune BERT** on your custom dataset using `Trainer` API
- **spaCy's training CLI** — custom NER and POS models
- **Gensim LDA** — topic modeling on large document collections
- **Kaggle NLP competitions** — real-world practice

### 🔗 Essential Resources
- [Hugging Face](https://huggingface.co/) — Models & Datasets hub
- [spaCy Docs](https://spacy.io/usage) — Production-ready NLP
- [NLTK Book (free)](https://www.nltk.org/book/) — Classic NLP textbook
- [Papers With Code — NLP](https://paperswithcode.com/area/natural-language-processing) — Latest research
- [Kaggle NLP](https://www.kaggle.com/search?q=NLP) — Datasets & notebooks

"""
